gc - Git command

diff --git a/zshrc-shared b/zshrc-shared
--- a/zshrc-shared
+++ b/zshrc-shared
@@ -180,6 +180,34 @@ gw()
 # ------------------------------------------------
 # GIT --------------------------------------------
 # ------------------------------------------------
+# Git command
+function gc()
+{
+  initial_arguments=$*
+
+  $*
+
+  if [[ $? == 0 ]] ; then
+
+    g_lso=`git ls-files --other --exclude-standard`
+
+    if [[ -n $g_lso ]] ; then
+        echo $g_lso
+        echo -en "\033[32;1mAdd these files to be tracked (y/n)?\033[0m "
+        read add_files
+
+        if [[ $add_files == "y" ]] ; then
+            git add .
+        fi
+    fi
+
+    git commit --all -m $initial_arguments
+  else
+    echo "fatal: Command failed. Not commiting."
+    return 1
+  fi
+}
+
 git-status-display()
 {
     # FIX: this says that the dir is clean when we deleted some files and when we git-mv files. probably more
